### ISSUE TITLE
Fails test when no '.' in @INC

### ISSUE THREAD

**Issue by jplesnik** [miyagawa/xml-atom#12]
On 5.26.0-RC1 , where '.' is not in @INC by default:

```
Can't locate t/TestLib.pm in @INC (you may need to install the t::TestLib module) (@INC contains: 
/builddir/build/BUILD/XML-Atom-0.42/blib/arch /builddir/build/BUILD/XML-Atom-0.42/blib/lib /usr/local/lib64/perl5 
/usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 
/usr/share/perl5) at t/11-entry.t line 5.
BEGIN failed--compilation aborted at t/11-entry.t line 5.
t/11-entry.t ..................... 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
```

**Comment by cschwenz** [comment]
```
t/04-person.t .................... ok
t/11-entry.t ..................... Can't locate t/TestLib.pm in @INC (you may need to install the t::TestLib module) (@INC contains: /Users/cal/.cpan/build/XML-Atom-0.42-0/blib/arch /Users/cal/.cpan/build/XML-Atom-0.42-0/blib/lib /Users/cal/perl5/perlbrew/perls/perl-5.26.0/lib/site_perl/5.26.0/darwin-thread-multi-ld-2level /Users/cal/perl5/perlbrew/perls/perl-5.26.0/lib/site_perl/5.26.0 /Users/cal/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/darwin-thread-multi-ld-2level /Users/cal/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0) at t/11-entry.t line 5.
BEGIN failed--compilation aborted at t/11-entry.t line 5.
t/11-entry.t ..................... Dubious, test returned 2 (wstat 512, 0x200)
No subtests run
t/12-feed.t ...................... ok
```

As can be seen above, this is still failing.

```
% perl -v

This is perl 5, version 26, subversion 0 (v5.26.0) built for darwin-thread-multi-ld-2level
(with 1 registered patch, see perl -V for more detail)

Copyright 1987-2017, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

%
```

As for why the above failure is important, this test fail is at minimum blocking the install of all modules in this list https://metacpan.org/requires/module/XML::Atom?sort=[[0,0]] (and likely more, as the aforementioned list only mentions direct uses of the `XML::Atom` module; modules which are one level removed from `XML::Atom` and are failing due to the above test failure include https://metacpan.org/requires/distribution/XML-Feed?sort=[[0,0]]).

**Comment by jkeenan** [comment]
> ```
> t/04-person.t .................... ok
> t/11-entry.t ..................... Can't locate t/TestLib.pm in @INC (you may need to install the t::TestLib module) (@INC contains: /Users/cal/.cpan/build/XML-Atom-0.42-0/blib/arch /Users/cal/.cpan/build/XML-Atom-0.42-0/blib/lib /Users/cal/perl5/perlbrew/perls/perl-5.26.0/lib/site_perl/5.26.0/darwin-thread-multi-ld-2level /Users/cal/perl5/perlbrew/perls/perl-5.26.0/lib/site_perl/5.26.0 /Users/cal/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/darwin-thread-multi-ld-2level /Users/cal/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0) at t/11-entry.t line 5.
> BEGIN failed--compilation aborted at t/11-entry.t line 5.
> t/11-entry.t ..................... Dubious, test returned 2 (wstat 512, 0x200)
> No subtests run
> t/12-feed.t ...................... ok
> ```
> 
> As can be seen above, this is still failing.
> 

This test failure was observed today when this module was tested against perl-5.31.9 on FreeBSD-11, threaded, as part of CPAN-River-3000 testing.

Can you investigate?

Thank you very much.
Jim Keenan

**Comment by perlpunk** [comment]
I think this can be closed
